development:
  nightly_run_cases_command:
    class: EnqueueRunNightlyCasesJob
    schedule: every day at 1 am

  #blazer_run_checks_daily:
  #  command: "Blazer.run_checks(schedule: 'hourly')"
  #  schedule: every hour    
  blazer_run_checks_daily:
    #class: RunBlazerChecksJob
    command: "Blazer.send_failing_checks"
    schedule: every hour


production:
  nightly_run_cases_command:
    class: EnqueueRunNightlyCasesJob
    schedule: every day at 1 am
    
  blazer_run_checks_daily:
    command: "Blazer.send_failing_checks"
    schedule: every day at 7 am
